import initTabNav from "./modules/tabnav.js";
import initAccordion from "./modules/accordion.js";
import initScroll from "./modules/initScroll.js";
import initAnimacaoScroll from "./modules/animacaoScroll.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropDownMenu from "./modules/dropdownMenu.js";
import initMenuMobile from './modules/menuMobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initanimaisNumeros from './modules/fecth-animais.js';
import initFecthBitcoin from './modules/fetch-bitcoin.js';

initTabNav();
initAccordion();
initScroll();
initAnimacaoScroll();
initModal();
initTooltip();
initDropDownMenu();
initMenuMobile();
initFuncionamento();
initanimaisNumeros();
initFecthBitcoin();